config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount PiccoBlog::Engine => "/blog"
  mount Thredded::Engine => '/forum'
  root to: 'home#index'
  get 'home/index'
  get '/question_summary/:post_id', to: 'posts#question_summariser', as: 'question_summariser'
  get '/post/:post_id/answers/:current_answer', to: 'posts#index', as: 'post_answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post, controller: :posts
  resources :posts do
    resources :post_summaries
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_one :post_summary
  self.primary_key = "Id"
end

app/models/post_summary.rb
class PostSummary < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.where(PostTypeId: 1).paginate(page: params[:page], per_page: 30)
  end
end

app/controllers/post_summaries_controller.rb
class PostSummariesController < ApplicationController
  def new
  end

  def create
    @post = Post.find(params[:post_id])
    @post_summary = @post.build_post_summary(summary_params)
    @post_summary.save
    redirect_back fallback_location: @post
  end
  def summary_params
    params.require(:post_summary).permit(:abstractive, :extractive)
  end
  def update
    @post = Post.find(params[:post_id])
    @post_summary = @post.post_summary.update_attributes(summary_params)
    redirect_back fallback_location: @post
  end

  def edit
  end

  def destroy
  end

  def index
  end

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def show
    @post = Post.find(params[:id])
    @post_answers = Post.where(ParentId: @post.Id)
  end
  def index
    p params[:current_answer]
    @post_answers_length = Post.where(ParentId: params[:post_id]).count()
    @post_answers = Post.where(ParentId: params[:post_id]).offset(params[:current_answer].to_i).first
    @post_summaries = PostSummary.find_by(post: @post_answers) || PostSummary.new(post: @post_answers)
  end
  def question_summariser
    @post = Post.find(params[:post_id])
    @post_summaries = PostSummary.joins(:post).where(posts: { ParentId: params[:post_id]})
    @new_post_summary = PostSummary.find_by(post: @post) || PostSummary.new(post: @post)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_summaries_helper.rb
module PostSummariesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= will_paginate @posts %>
<table>
  <tr>
    <td><b>Id</b></td>
    <td><b>Title</b></td>
    <td><b>Body</b></td>
    <td><b>Edit</b></td>
    <td><b>Edit Status</b></td>
  </tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.Id %></td>
      <td><%= post.Title %></td>
      <td><%= post.Body[0...100] %></td>
      <td><%= link_to "Edit", post_path(id: post.Id) %></td>
      <td>UnEdited</td>
    </tr>
  <% end %>
</table>
<%= will_paginate @posts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Research</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'NLP Research', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>

  <%= yield :top_content %>

  <div class="container">
    <h1><%= yield :header %></h1>
    <%= yield %>
  </div>
  </body>
</html>

app/views/post_summaries/create.html.erb
<h1>PostSummaries#create</h1>
<p>Find me in app/views/post_summaries/create.html.erb</p>

app/views/post_summaries/destroy.html.erb
<h1>PostSummaries#destroy</h1>
<p>Find me in app/views/post_summaries/destroy.html.erb</p>

app/views/post_summaries/edit.html.erb
<h1>PostSummaries#edit</h1>
<p>Find me in app/views/post_summaries/edit.html.erb</p>

app/views/post_summaries/index.html.erb
<h1>PostSummaries#index</h1>
<p>Find me in app/views/post_summaries/index.html.erb</p>

app/views/post_summaries/new.html.erb
<h1>PostSummaries#new</h1>
<p>Find me in app/views/post_summaries/new.html.erb</p>

app/views/post_summaries/show.html.erb
<h1>PostSummaries#show</h1>
<p>Find me in app/views/post_summaries/show.html.erb</p>

app/views/post_summaries/update.html.erb
<h1>PostSummaries#update</h1>
<p>Find me in app/views/post_summaries/update.html.erb</p>

app/views/posts/index.html.erb
<%= @post_answers.Body %>

<%= form_for [@post_answers, @post_summaries] do |f| %>
  <%= f.label 'Abstractive' %>
  <%= f.text_area :abstractive %>
  <br /><br />
  <%= f.label :extractive %>
  <%= f.text_field :extractive %>
  <br /><br />
  <%= f.submit %>
<% end %>
  <% if (params[:current_answer].to_i > 0) %>
  <%= link_to "Previous", post_answer_path(post_id: params[:post_id], current_answer: params[:current_answer].to_i - 1) %>
  <% end %>
  <% if (params[:current_answer].to_i < @post_answers_length - 1) %>
    <%= link_to "Next", post_answer_path(post_id: params[:post_id], current_answer: params[:current_answer].to_i + 1) %>
  <% end %>
  <% if (params[:current_answer].to_i == @post_answers_length - 1) %>
    <%= link_to "Summarise all summaries", question_summariser_path(post_id: params[:post_id]) %>

<% end %>

app/views/posts/question_summariser.html.erb
<%= @post.Body %>

<% @post_summaries.each_with_index do |post_summary, idx| %>
  <tr>
    <td><%= post_summary.abstractive %></td>
    <td><%= post_summary.extractive %></td>
  </tr>
<% end %>

<%= form_for [@post, @new_post_summary] do |f| %>
  <%= f.label 'Abstractive' %>
  <%= f.text_area :abstractive %>
  <br /><br />
  <%= f.label :extractive %>
  <%= f.text_field :extractive %>
  <br /><br />
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= @post.Body %>

<table>
  <tr>
    <td><b>Id</b></td>
    <td><b>Title</b></td>
    <td><b>Body</b></td>
    <td><b>Edit</b></td>
    <td><b>Edit Status</b></td>
  </tr>
<% @post_answers.each_with_index do |post, idx| %>
  <tr>
    <td><%= post.Id %></td>
    <td><%= post.Title %></td>
    <td><%= post.Body[0...100] %></td>
    <td><%= link_to "Edit", post_answer_path(post_id: @post.Id, current_answer: idx) %></td>
    <td>UnEdited</td>
  </tr>
<% end %>
</table>